### ISSUE TITLE
License type?

### ISSUE THREAD

**Issue by lni** [zergon321/ll#1]
Hi there, thanks for sharing the code. I'd like to use this in one of my projects if you can license it under Apache2, MIT or BSD, putting it under public domain surely will also work. 

Could you please add a license? 

Cheers.

**Comment by zergon321** [comment]
Added a MIT license file.

**Comment by lni** [comment]
Thanks a lot!

**Comment by AbstractsMachine** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
